#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../../vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Webman\Generator\Command\CrudCommand;

$application = new Application('Webman Generator', '1.0.0');
$application->add(new CrudCommand());
$application->run(); 